variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  BUILDKIT_PROGRESS: "plain"
cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - poetry install

dev images:
  tags: ['docker-shell']
  script:
    - black --check ogscm
    - poetry run python ogscm/general_cli.py ogscm/recipes/compiler.py ogscm/recipes/ogs.py -B -C --sif_file ubuntu-dev.sif --pm system --ogs off
    - poetry run python ogscm/general_cli.py ogscm/recipes/compiler.py ogscm/recipes/ogs.py -B -C --sif_file centos-dev.sif --base_image centos:8 --pm system --ogs off
  artifacts:
    # example URL:
    # https://gitlab.opengeosys.org/ogs/container-maker/-/jobs/artifacts/master/raw/_out/images/ubuntu-dev.sif?job=dev+images
    paths:
      - _out/images/*.sif

publish:
  tags: ['docker-shell']
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG != null'
  script:
    - poetry build
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
