image: python:3
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - venv/
variables:
  PYTHONPATH: "${PYTHONPATH}:."

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

dev images:
  tags: ['docker-shell']
  script:
    - python ogscm/cli.py -B -C --sif_file ubuntu-dev.sif --pm system --ogs off
    - python ogscm/cli.py -B -C --sif_file centos-dev.sif --base_image centos:8 --pm system --ogs off
  artifacts:
    # example URL:
    # https://gitlab.opengeosys.org/ogs/container-maker/-/jobs/artifacts/master/raw/_out/images/ubuntu-dev.sif?job=dev+images
    paths:
      - _out/images/*.sif

publish:
  tags: ['docker-shell']
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG != ""'
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
